username: bryantmejia242@gmail.com
password: bornBillionaire2024
# username: art.bryantfeed@gmail.com
# password: newaccount123
# username: bmejia220@gmail.com
# password: Krxpjhs)#JCD2ax

first_name: Bryant
last_name: Mejia
salary: 195000
experience: 7
address:
city: New York
state: NY
zipcode: 10011
country: United States

phone_number: 5707901185
positions:
- Senior Software Engineer
- Software Engineer
- Full Stack Developer
- Backend Engineer
- Nodejs

locations:
- Remote
- New York

# --------- Optional Parameters -------
uploads:
 Resume: '/Users/vibrantceo/easy-apply-bot/bryant-mejia-software-engineer-07012024.docx'
 Cover Letter: '/Users/vibrantceo/easy-apply-bot/cover-letter.rtf'
#  Photo: # PATH TO photo


# output_filename:
# - # PATH TO OUTPUT FILE (default output.csv)

# blacklist:
# - # Company names you want to ignore

blackListTitles:
- Data Scientist